defaultRules:
  rules:
    general: false
    etcd: false
    kubeApiserver: false
    kubeApiserverAvailability: false
    kubeApiserverError: false
    kubeApiserverSlos: false
    kubeScheduler: false
  labels:
    cluster: iris
  additionalRuleLabels:
    cluster: iris

kubeControllerManager:
  enabled: false    

coreDns:
  enabled: false

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes:
          - "ReadWriteOnce"
          resources:
            requests:
              storage: 2Gi
  
  additionalServiceMonitors:
  - name: iris
    endpoints:
    - interval: 15s
      path: /api/monitor/metrics
      port: webserver
      relabelings:
      - targetLabel: application
        replacement: iris
    namespaceSelector:
      matchNames:
      - iris
    selector:
      matchLabels:
        intersystems.com/name: iris
    
grafana:
  enabled: true

  persistence:
    type: pvc
    enabled: true
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    size: 2Gi
  
  grafana.ini:
    server:
      root_url: http://example.com/grafana/
      serve_from_sub_path: true
  
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      cert-manager.io/cluster-issuer: lets-encrypt-staging
    hosts:
    - example.com
    path: /grafana/?(.*)
    pathType: ImplementationSpecific
    tls:
    - secretName: grafana-tls
      hosts:
      - example.com
  
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        url: http://loki-headless.logging:3100
        isDefault: false
        editable: true
        readOnly: true
  
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  